#cloud-config
package_update: true
package_upgrade: true

users:
  - name: francisco
    groups: sudo,docker
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKaMjMl8lDMaFXUdsDw7KV/R4of0onkdGTzz3EahgFJmPTbxi+upBBpK+F86TqDvuRE8WSTc7YUGI6awNA1aT9c7+O8FsMazmFIXArrp09W6OSv2F+Pz7o/L7oiIEI5CPfcDhlEiH0/vOMuoxymhU+YZPH3mHAhZmj/Pp+jxfjAr4pc1cJENtAX694sOnpo4erMgc/2tEpY7nJ4DcXDQRl2U+V3vvIY6jPmycPdHnWED4U/zzYOprRQhVu/CmghkD6iQ+0RtYDRSMQvsViYvvz7GRW1URfT3z92LcdDHkK5KRLY68yjuto+VzghzXxWWneN2jDXoudckW3NRINQ/3l CarIoT-Project

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - apt-get install -y docker-compose
  - apt-get install -y docker-compose-plugin
  - apt-get install -y git
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker francisco
  - newgrp docker

 # Create home and set permissions
  - mkdir -p /home/francisco
  - chown -R francisco:francisco /home/francisco