#cloud-config
package_update: true
package_upgrade: true

users:
  - name: francisco
    groups: sudo,docker
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKaMjMl8lDMaFXUdsDw7KV/R4of0onkdGTzz3EahgFJmPTbxi+upBBpK+F86TqDvuRE8WSTc7YUGI6awNA1aT9c7+O8FsMazmFIXArrp09W6OSv2F+Pz7o/L7oiIEI5CPfcDhlEiH0/vOMuoxymhU+YZPH3mHAhZmj/Pp+jxfjAr4pc1cJENtAX694sOnpo4erMgc/2tEpY7nJ4DcXDQRl2U+V3vvIY6jPmycPdHnWED4U/zzYOprRQhVu/CmghkD6iQ+0RtYDRSMQvsViYvvz7GRW1URfT3z92LcdDHkK5KRLY68yjuto+VzghzXxWWneN2jDXoudckW3NRINQ/3l CarIoT-Project

runcmd:
  # Install Docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - usermod -aG docker francisco
  - systemctl enable docker
  - systemctl start docker

  # Install Docker Compose v2 (plugin for `docker compose`)
  - apt-get install -y docker-compose-plugin

  # Install Docker Compose v1 (classic `docker-compose`)
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # Install Git
  - apt-get install -y git

  # Create home and set permissions
  - mkdir -p /home/francisco
  - chown -R francisco:francisco /home/francisco

  # Write Rancher Docker Compose YAML (with privileged mode)
  - |
    cat <<EOF > /home/francisco/rancher-server.yaml
    services:
      rancher:
        image: rancher/rancher:latest
        container_name: rancher
        restart: unless-stopped
        privileged: true
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - rancher-data:/var/lib/rancher
    volumes:
      rancher-data:
    EOF

  # Set file ownership
  - chown francisco:francisco /home/francisco/rancher-server.yaml

  # Start Rancher using modern `docker compose` as francisco
  - su - francisco -c "docker compose -f /home/francisco/rancher-server.yaml up -d"

final_message: " Rancher server setup complete. Access it at https://<server_ip>/"
