services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    privileged: true
    ports:
      - "443:443"
    volumes:
      - rancher-data:/var/lib/rancher
volumes:
  rancher-data:
